### ISSUE TITLE
Workshop video download link is broken

### ISSUE THREAD

**Issue by Fariba-azhdarpour** [fardinayar/aaic_od#1]
Hi, 
When I click on the link provided here: [https://drive.google.com/file/d/1PNLkQhGLZxXMptqL4TD5Jq558_s_U_L_/view?usp=sharing],
I receive a error message, indicating that the video is no longer available.

(
Sorry, the file you have requested does not exist.
Make sure that you have the correct URL and the file exists.
)

**Comment by fardinayar** [comment]
Hi Fariba,
Unfortunately, I think I mistakenly removed it a few months ago, and I don't have any backup :(
Sorry about that. Feel free to ask me any question about mmdetection or object detection algorithms  in general.
